version: '3.9'
services:    
  app:
    build: .
    ports:
      - '80:8080'
    depends_on:
      - mongoserver

  mongoserver:
    image: 'mongo:6.0'
    ports:
      - '27017:27017'
    volumes:
      - 'mongodata:/data/db'

volumes:
  mongodata: